### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by 5oclockshadow** [Ichinga-Samuel/aiomql#10]
(testaiomql) PS C:\Users\Radha\Documents\Company> python --version
Python 3.11.0
(testaiomql) PS C:\Users\Radha\Documents\Company> pip show aiomql
Name: aiomql
Version: 3.23
Summary: Asynchronous MetaTrader5 library and Algorithmic Trading Framework
Home-page: https://github.com/Ichinga-Samuel/aiomql
Author: Ichinga Samuel
Author-email: ichingasamuel@gmail.com
License: MIT
Location: C:\Users\Radha\anaconda3\envs\testaiomql\Lib\site-packages
Requires: matplotlib, MetaTrader5, mplfinance, pandas, pandas-ta
Required-by:
(testaiomql) PS C:\Users\Radha\Documents\Company> python --version
Python 3.11.0
(testaiomql) PS C:\Users\Radha\Documents\Company> python .\WiseBotTest.py
Error in obtaining symbols.:Terminal: Incompatible versions, please install the latest version of Terminal and Python module
None
(testaiomql) PS C:\Users\Radha\Documents\Company>

**Comment by Ichinga-Samuel** [comment]
Please use the library from pip. Not directly from the repo. It is undergoing a **Major** upgrade.
