### ISSUE TITLE
TradeResult

### ISSUE THREAD

**Issue by kamranshalilian** [Ichinga-Samuel/aiomql#3]
hey friend 
I think that you remove TradeResult
but in file /src/aiomql/lib/traders/simple_deal_trader.py
you use it

```
from .trade_result import TradeResult

 
 result.profit = await self.order.calc_profit()
 await TradeResult(result=result, parameters=params).save()      #line 60

```

**Comment by Ichinga-Samuel** [comment]
It is actually in the library but was somehow ignored in the push to remote.

This has been resolved. For best results please uninstall and re-install the package
