### ISSUE TITLE
Optimization and Structural Enhancement of Trading System

### ISSUE THREAD

**Issue by zinzinday** [Ichinga-Samuel/aiomql#6]
I have reviewed the system structure. You have built almost all the features to handle the MT5 API integration smoothly and optimally. However, there are still some areas that can be optimized further:

1. **Symbol Buffer Optimization**
    - The `copy_rates_*` functions should store the previously updated data and only update the missing candles from the last update time.
    - Similarly, for `copy_ticks_*`.

2. **Trading Strategy Execution Structure**
    - A basic abstract base class (ABC) singleton (Symbol, Magic) should be created to define the structure of campaign components more flexibly. This should include:
        - **DataProcessing**: Handling updates of rates, indicator calculations, signal detection, etc.
        - **Events**:
            - `OnTick`: Listening for tick changes.
            - `OnSignal`
            - `OnTarget`
        - **Analytics**:
            - Deals, Reports (Alerts, to_pdf, to_xsl, etc.)
            - Orders
            - Positions

3. **Backtesting Integration**
    - It would be excellent if we could add backtesting functionality.
    - MT5 integration does not support backtesting directly. We can only use `copy_ticks_*` if we want to backtest with real ticks, or use the M1 timeframe and resample it into higher timeframes to backtest across multiple timeframes simultaneously.
    - Additionally, we need to build an order simulation to track the backtest process when orders are filled or targets are hit, etc.
    - Finally, we must report on our strategy.

#### Benefits
Implementing these optimizations and structural enhancements will:
- Improve the efficiency of data updates by reducing redundant data fetching.
- Provide a flexible and extensible framework for defining and executing trading strategies.
- Facilitate better organization and separation of concerns within the system.
- Enable comprehensive backtesting of strategies, providing valuable insights into their performance before live trading.

#### Suggested Implementation Steps
1. Modify the `copy_rates_*` functions to check and store the last updated data and only fetch new candles since the last update.
2. Apply a similar approach to the `copy_ticks_*` functions.
3. Design and implement a basic ABC singleton class for trading strategies, encapsulating the suggested components (DataProcessing, Events, Analytics).
4. Develop a backtesting module:
    - Implement tick data handling and M1 timeframe resampling for multi-timeframe backtesting.
    - Create an order simulation mechanism to track order fills and target hits during the backtest.
    - Generate comprehensive reports on strategy performance.

Your contributions have been very useful and appreciated. Looking forward to further improvements and discussions, especially regarding the backtesting implementation. 1+)

**Comment by Ichinga-Samuel** [comment]
Thanks for your insights and observations. I am currently working on some of these features although, not at the desired pace. Feel free to contribute.

**Comment by gabrielfast** [comment]
Something that could help in the backtest would be to change the Strategy.trade method from an infinite loop to an on_tick method that would be called at each tick of the symbol.

When registering the strategy, you could store the class instance and create a tick monitor for each symbol. If there is a new tick, you could call the on_tick method of the stored instances. The mdapena/pyventus package could help you with this.

I believe that changing this concept would help in the backtests because when you create the tick simulator, you just need to call the new Strategy.on_tick function for each tick.

**Comment by Ichinga-Samuel** [comment]
Check out version 4.0.0. More features will be added later, but most importantly, there is a backtester. Hurray!!!
