### ISSUE TITLE
'ForexSymbol' object has no attribute 'volume_min'

### ISSUE THREAD

**Issue by 5oclockshadow** [Ichinga-Samuel/aiomql#7]
2024-10-13 17:35:00,159 - ERROR - 'ForexSymbol' object has no attribute 'volume_min' in SimpleTrader.place_trade for USDJPY.s

I get the above error when trying to run the framework out of the box with no mods... Any ideas or help on how to properly fix.?

**Comment by Ichinga-Samuel** [comment]
1. Make sure you are connected to the terminal.
2. Make sure you have pulled the symbol data from the terminal using _symbol.init_.
3. Simple trader is a simple implementation to show how you can use the Trader class, so make sure it is actually what you need.
